### ISSUE TITLE
example からファイルを読み込んだ際、座標画面にファイル名が正しく表示されない

### ISSUE THREAD

**Issue by imaren** [HydLa/webHydLa#103]
example から例題を読み込み、実行した際に、座標画面に表示されるファイル名がすべてデフォルトの "bouncing_ball" になってしまう。

https://github.com/HydLa/webHydLa/blob/a7426ae6f5a4af4bf0d557e62c4b58f04df40c1e/src/graph/graph.ts#L110-L129

**Comment by sano-jin** [comment]
hydat を load するときは，上記関数 modifyNameLabel が呼ばれるけど，hydla のプログラムを load するときは呼ばれていないっぽいです．

## 解決策
https://github.com/HydLa/webHydLa/blob/56d53700e74fac995bc350641aafa3f049a39699/src/editor/example.ts#L39-L44

に
```typescript
modifyNameLabel(filename);
```
を追加するだけだと思います（import する必要もあります）．
