### ISSUE TITLE
グラフのズーム機能切り替え時にエディタサイズが変わってしまう

### ISSUE THREAD

**Issue by k-yamada39** [HydLa/webHydLa#114]
webHydLaではshiftキーなどを用いて下部のグラフのズーム機能を有効化できるが、その際ウィンドウ右部のスクロールバーが非表示になる。
この時テキストエディタの横幅がそれに応じて変化してしまい、テキスト編集時に煩わしく感じる。
特にshiftキーに関しては、モジュールの名前定義のため大文字入力をする際などに押すことが多いため、モジュール定義のたびにエディタサイズが変わってしまうのはあまり快適ではない。

![38tkFCxbfPzCJOJorZj61631765428-1631765441](https://user-images.githubusercontent.com/84457656/133548816-a1011ca9-d513-4634-a8b7-d445b6449246.gif)

**Comment by sano-jin** [comment]
ありがとうございます！
gif 画像，わかりやすくてめちゃめちゃ良いですね〜（今度どうやってやったのか聞こうかな😆）
