### ISSUE TITLE
グラフエリアの左下のファイル名表示について

### ISSUE THREAD

**Issue by yuhtota** [HydLa/webHydLa#119]
グラフエリアの左下のファイル名表示は、なくても（ないほうが）いい気がします。

このファイル名表示は、エディタエリアの SAVE/LOAD の Examples または Load File で選択したファイルに対して行われますが、Load FIle はローカルからファイルを持ってくる必要があります。しかし、自分で書いたプログラムはリモート（pecorino）に置いてあるため、Load File ではなく、コピペでエディタエリアにそのプログラムを貼り付けるという風にしています（リモートから直接 Load File はできないですよね？）。当然ですが、コピペの場合はそのファイル名は反映されないので、表示されているファイル名（プログラム）と実行しているプログラムが異なるということが起こり得ます。これは、画面を見せて説明するとき（特にオンライン）やスクショ等でその画像を載せるときなど、あまりよくないことかなと考えます（訂正を必要とするのは利用者側の手間にもなる）。

他の人（特に秦さん？）が自分で書いたプログラムを webHydLa で実行するときどうしているかも含めて検討してもらえるとありがたいです。

**Comment by sano-jin** [comment]
（部外者ですが）一応思ったこと：

まぁ使ったことのない（使わない）人間からすると，
「メンテのためには余計なものはできるだけ廃したい」
ですね（個人的な哲学の影響が大きいのであまり真面目に相手にする必要はないです😆）．

この表示は元々は画面全体を覆う canvas を上から被せるという謎の手法（なんで？）になっていたのですが，それを div 要素（span だったかも）にぼくが変えました．

が，背景との兼ね合い（グラフエリアの背景色は変えられるけど，この文字色は変えられなくて良いのか）とかどうするのが正解なんだろーなぁと思った記憶．

**Comment by khata1007** [comment]
僕も webHydLa 上でコードを書くのが初手になることはほぼ無いし、基本 vscode からのコピペになるので無くていい派ではあります。ファイルの読み込みにはボタン操作何回も挟むので操作コストが…
いずれにせよグラフ描画の画面にファイル名は無くていいとは思うので、一度消してしまうのがいいかもという個人の見解です
