### ISSUE TITLE
"GET /theme-sqlserver.js HTTP/1.1" 404

### ISSUE THREAD

**Issue by sapphimoor** [HydLa/webHydLa#135]
pecorino 上でサーバを動かして手元で webHydLa を起動すると、
サーバ上のコンソールにて `"GET /theme-sqlserver.js HTTP/1.1" 404` が発生する。

**Comment by sano-jin** [comment]
（おそらく）ace（ブラウザ上で editor を提供するためのパッケージ）のテーマをロードしようとする段階で get できなくてエラーになっている．

**Comment by sano-jin** [comment]
最新の develop（7c31c9c644771ddb051f5d2ce6db7240c44eb2cf）で確認
