### ISSUE TITLE
乗算の式の print の際に括弧を省いてしまっている

### ISSUE THREAD

**Issue by sano-jin** [HydLa/webHydLa#76]
parse.ts の乗算・除算の式などの toString メソッドでは括弧を省いている．
https://github.com/HydLa/webHydLa/blob/52e902494b727b2a7bfc3d45dcab15021d83dc07/src/hydat/parse.ts#L274

が，もっと優先度の高い演算子 `^` があるためにこれはまずいのではないか？
- `x ^ (y * z)` とか

質問：
1. これは仕様ですか（バグですか）？
2. 修正する際は，単に括弧をつければ良いでしょうか？それとももっと綺麗に（括弧を省いて）pretty print する関数を実装した方が良いでしょうか？

**Comment by nikosai** [comment]
1. 単にバグの気がします。
2. カッコを付けるのが安全側。pretty printはトンデモ面倒なので別途（必要に迫られたら）やることにしておくのが良いかと。

**Comment by sano-jin** [comment]
了解です．
ありがとうございます🙇
やっときます．
